grails-app/domain/com/kist/maitidevi/AreasOfLife.groovy
package com.kist.maitidevi

class AreasOfLife {
	String label
	String color
	Integer value
	String highlight
	
    static constraints = {
		value inList:['1','2','3','4','5','6','7','8','9','10']
		
    }
}

grails-app/domain/com/kist/maitidevi/Visitor.groovy
package com.kist.maitidevi

class Visitor {
	String firstName
	String lastName
	String email
	

    static constraints = {
		firstName blank:false, nullable:false, size:1..25
		lastName blank:false, nullable:false, size:1..25
		email email:true, blank:false, nulable:false 
		
    }
}

grails-app/controllers/com/kist/maitidevi/AreasOfLifeController.groovy
package com.kist.maitidevi



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class AreasOfLifeController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond AreasOfLife.list(params), model:[areasOfLifeInstanceCount: AreasOfLife.count()]
    }

    def show(AreasOfLife areasOfLifeInstance) {
        respond areasOfLifeInstance
    }

    def create() {
        respond new AreasOfLife(params)
    }

    @Transactional
    def save(AreasOfLife areasOfLifeInstance) {
        if (areasOfLifeInstance == null) {
            notFound()
            return
        }

        if (areasOfLifeInstance.hasErrors()) {
            respond areasOfLifeInstance.errors, view:'create'
            return
        }

        areasOfLifeInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'areasOfLife.label', default: 'AreasOfLife'), areasOfLifeInstance.id])
                redirect areasOfLifeInstance
            }
            '*' { respond areasOfLifeInstance, [status: CREATED] }
        }
    }

    def edit(AreasOfLife areasOfLifeInstance) {
        respond areasOfLifeInstance
    }

    @Transactional
    def update(AreasOfLife areasOfLifeInstance) {
        if (areasOfLifeInstance == null) {
            notFound()
            return
        }

        if (areasOfLifeInstance.hasErrors()) {
            respond areasOfLifeInstance.errors, view:'edit'
            return
        }

        areasOfLifeInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'AreasOfLife.label', default: 'AreasOfLife'), areasOfLifeInstance.id])
                redirect areasOfLifeInstance
            }
            '*'{ respond areasOfLifeInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(AreasOfLife areasOfLifeInstance) {

        if (areasOfLifeInstance == null) {
            notFound()
            return
        }

        areasOfLifeInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'AreasOfLife.label', default: 'AreasOfLife'), areasOfLifeInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'areasOfLife.label', default: 'AreasOfLife'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/com/kist/maitidevi/PublicController.groovy
package com.kist.maitidevi

class PublicController {

    def index() { }
	def visitor() { }
	def area() { }
	def output() { }
}

grails-app/controllers/com/kist/maitidevi/VisitorController.groovy
package com.kist.maitidevi



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class VisitorController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Visitor.list(params), model:[visitorInstanceCount: Visitor.count()]
    }

    def show(Visitor visitorInstance) {
        respond visitorInstance
    }

    def create() {
        respond new Visitor(params)
    }

    @Transactional
    def save(Visitor visitorInstance) {
        if (visitorInstance == null) {
            notFound()
            return
        }

        if (visitorInstance.hasErrors()) {
            respond visitorInstance.errors, view:'create'
            return
        }

        visitorInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'visitor.label', default: 'Visitor'), visitorInstance.id])
                redirect visitorInstance
            }
            '*' { respond visitorInstance, [status: CREATED] }
        }
    }

    def edit(Visitor visitorInstance) {
        respond visitorInstance
    }

    @Transactional
    def update(Visitor visitorInstance) {
        if (visitorInstance == null) {
            notFound()
            return
        }

        if (visitorInstance.hasErrors()) {
            respond visitorInstance.errors, view:'edit'
            return
        }

        visitorInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Visitor.label', default: 'Visitor'), visitorInstance.id])
                redirect visitorInstance
            }
            '*'{ respond visitorInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Visitor visitorInstance) {

        if (visitorInstance == null) {
            notFound()
            return
        }

        visitorInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Visitor.label', default: 'Visitor'), visitorInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'visitor.label', default: 'Visitor'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/areasOfLife/_form.gsp
<%@ page import="com.kist.maitidevi.AreasOfLife" %>



<div class="fieldcontain ${hasErrors(bean: areasOfLifeInstance, field: 'value', 'error')} required">
	<label for="value">
		<g:message code="areasOfLife.value.label" default="Value" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="value" from="${areasOfLifeInstance.constraints.value.inList}" required="" value="${fieldValue(bean: areasOfLifeInstance, field: 'value')}" valueMessagePrefix="areasOfLife.value"/>

</div>

<div class="fieldcontain ${hasErrors(bean: areasOfLifeInstance, field: 'color', 'error')} required">
	<label for="color">
		<g:message code="areasOfLife.color.label" default="Color" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="color" required="" value="${areasOfLifeInstance?.color}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: areasOfLifeInstance, field: 'highlight', 'error')} required">
	<label for="highlight">
		<g:message code="areasOfLife.highlight.label" default="Highlight" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="highlight" required="" value="${areasOfLifeInstance?.highlight}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: areasOfLifeInstance, field: 'label', 'error')} required">
	<label for="label">
		<g:message code="areasOfLife.label.label" default="Label" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="label" required="" value="${areasOfLifeInstance?.label}"/>

</div>

grails-app/views/areasOfLife/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'areasOfLife.label', default: 'AreasOfLife')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-areasOfLife" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-areasOfLife" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${areasOfLifeInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${areasOfLifeInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:areasOfLifeInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/areasOfLife/edit.gsp
<%@ page import="com.kist.maitidevi.AreasOfLife" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'areasOfLife.label', default: 'AreasOfLife')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-areasOfLife" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-areasOfLife" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${areasOfLifeInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${areasOfLifeInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:areasOfLifeInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${areasOfLifeInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/areasOfLife/index.gsp
<%@ page import="com.kist.maitidevi.AreasOfLife" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'areasOfLife.label', default: 'AreasOfLife')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-areasOfLife" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-areasOfLife" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="value" title="${message(code: 'areasOfLife.value.label', default: 'Value')}" />
					
						<g:sortableColumn property="color" title="${message(code: 'areasOfLife.color.label', default: 'Color')}" />
					
						<g:sortableColumn property="highlight" title="${message(code: 'areasOfLife.highlight.label', default: 'Highlight')}" />
					
						<g:sortableColumn property="label" title="${message(code: 'areasOfLife.label.label', default: 'Label')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${areasOfLifeInstanceList}" status="i" var="areasOfLifeInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${areasOfLifeInstance.id}">${fieldValue(bean: areasOfLifeInstance, field: "value")}</g:link></td>
					
						<td>${fieldValue(bean: areasOfLifeInstance, field: "color")}</td>
					
						<td>${fieldValue(bean: areasOfLifeInstance, field: "highlight")}</td>
					
						<td>${fieldValue(bean: areasOfLifeInstance, field: "label")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${areasOfLifeInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/areasOfLife/show.gsp
<%@ page import="com.kist.maitidevi.AreasOfLife" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'areasOfLife.label', default: 'AreasOfLife')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-areasOfLife" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-areasOfLife" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list areasOfLife">
			
				<g:if test="${areasOfLifeInstance?.value}">
				<li class="fieldcontain">
					<span id="value-label" class="property-label"><g:message code="areasOfLife.value.label" default="Value" /></span>
					
						<span class="property-value" aria-labelledby="value-label"><g:fieldValue bean="${areasOfLifeInstance}" field="value"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${areasOfLifeInstance?.color}">
				<li class="fieldcontain">
					<span id="color-label" class="property-label"><g:message code="areasOfLife.color.label" default="Color" /></span>
					
						<span class="property-value" aria-labelledby="color-label"><g:fieldValue bean="${areasOfLifeInstance}" field="color"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${areasOfLifeInstance?.highlight}">
				<li class="fieldcontain">
					<span id="highlight-label" class="property-label"><g:message code="areasOfLife.highlight.label" default="Highlight" /></span>
					
						<span class="property-value" aria-labelledby="highlight-label"><g:fieldValue bean="${areasOfLifeInstance}" field="highlight"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${areasOfLifeInstance?.label}">
				<li class="fieldcontain">
					<span id="label-label" class="property-label"><g:message code="areasOfLife.label.label" default="Label" /></span>
					
						<span class="property-value" aria-labelledby="label-label"><g:fieldValue bean="${areasOfLifeInstance}" field="label"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:areasOfLifeInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${areasOfLifeInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${assetPath(src: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${assetPath(src: 'apple-touch-icon-retina.png')}">
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
		<g:layoutHead/>
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><asset:image src="grails_logo.png" alt="Grails"/></a></div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
	</body>
</html>

grails-app/views/visitor/_form.gsp
<%@ page import="com.kist.maitidevi.Visitor" %>



<div class="fieldcontain ${hasErrors(bean: visitorInstance, field: 'firstName', 'error')} required">
	<label for="firstName">
		<g:message code="visitor.firstName.label" default="First Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="firstName" maxlength="25" required="" value="${visitorInstance?.firstName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: visitorInstance, field: 'lastName', 'error')} required">
	<label for="lastName">
		<g:message code="visitor.lastName.label" default="Last Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="lastName" maxlength="25" required="" value="${visitorInstance?.lastName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: visitorInstance, field: 'email', 'error')} required">
	<label for="email">
		<g:message code="visitor.email.label" default="Email" />
		<span class="required-indicator">*</span>
	</label>
	<g:field type="email" name="email" required="" value="${visitorInstance?.email}"/>

</div>

grails-app/views/visitor/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'visitor.label', default: 'Visitor')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-visitor" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-visitor" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${visitorInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${visitorInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:visitorInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/visitor/edit.gsp
<%@ page import="com.kist.maitidevi.Visitor" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'visitor.label', default: 'Visitor')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-visitor" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-visitor" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${visitorInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${visitorInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:visitorInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${visitorInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/visitor/index.gsp
<%@ page import="com.kist.maitidevi.Visitor" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'visitor.label', default: 'Visitor')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-visitor" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-visitor" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="firstName" title="${message(code: 'visitor.firstName.label', default: 'First Name')}" />
					
						<g:sortableColumn property="lastName" title="${message(code: 'visitor.lastName.label', default: 'Last Name')}" />
					
						<g:sortableColumn property="email" title="${message(code: 'visitor.email.label', default: 'Email')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${visitorInstanceList}" status="i" var="visitorInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${visitorInstance.id}">${fieldValue(bean: visitorInstance, field: "firstName")}</g:link></td>
					
						<td>${fieldValue(bean: visitorInstance, field: "lastName")}</td>
					
						<td>${fieldValue(bean: visitorInstance, field: "email")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${visitorInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/visitor/show.gsp
<%@ page import="com.kist.maitidevi.Visitor" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'visitor.label', default: 'Visitor')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-visitor" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-visitor" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list visitor">
			
				<g:if test="${visitorInstance?.firstName}">
				<li class="fieldcontain">
					<span id="firstName-label" class="property-label"><g:message code="visitor.firstName.label" default="First Name" /></span>
					
						<span class="property-value" aria-labelledby="firstName-label"><g:fieldValue bean="${visitorInstance}" field="firstName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${visitorInstance?.lastName}">
				<li class="fieldcontain">
					<span id="lastName-label" class="property-label"><g:message code="visitor.lastName.label" default="Last Name" /></span>
					
						<span class="property-value" aria-labelledby="lastName-label"><g:fieldValue bean="${visitorInstance}" field="lastName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${visitorInstance?.email}">
				<li class="fieldcontain">
					<span id="email-label" class="property-label"><g:message code="visitor.email.label" default="Email" /></span>
					
						<span class="property-value" aria-labelledby="email-label"><g:fieldValue bean="${visitorInstance}" field="email"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:visitorInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${visitorInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>